[options]
Architecture = auto
SigLevel = Required DatabaseOptional
HoldPkg = pacman glibc
CheckSpace

#[core-testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

#[extra-testing]
#Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[zotix]
SigLevel = Optional TrustAll
Server = https://zotixos-repo.onrender.com
