autoPartition: true
useEntireDisk: true
eraseDisk: true

defaultFilesystem: btrfs

availableFilesystems:
  - btrfs
  - ext4
  - xfs


btrfsConfig:
  subvolumes:
    - name: "@"
      mountPoint: "/"
    - name: "@boot"
      mountPoint: "/boot/efi"
    - name: "@home"
      mountPoint: "/home"
    - name: "@snapshots"
      mountPoint: "/.snapshots"

bootloader: grub
efi: true
