id: zotixos-welcome

strings:
  logo: /usr/local/lib/logo.svg
  productName: "ZotixOS"
  version: "0.1.0"

  welcomeMessage: "Welcome to ZotixOS"
  description: "An Arch-based system with simplicity and system protection."
