modules-search:
  - /etc/calamares/modules
  - /usr/share/calamares/modules

sequence:
  - show: welcome
  - show: location
  - show: partition
  - show: zotixos-warning
  - show: users
  - show: summary
  - exec: install
  - show: finish
